image:
  link_1: "http://placehold.it/128x128"
validation:
  user:
    name_size: 50
    email_size: 50
    password_size: 6
    format:
      email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
category:
  length: 200
book:
  description:
    length: 1000
  quantity:
    length: 100
panigate:
  category: 5
  book: 6
  borrowing: 10
author:
  length:
    name: 50
    story: 1000
    birth: 20
limit_book: 4
borrow:
  exist: 1
random: 10
number: 1
convert_date: "%m/%d/%Y"
date: 7
quantity: 0
rouding: 1
point: 5
status:
  pending: 0
enum:
  payed: 3
